#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Console\MakeDtosCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new MakeDtosCommand());

$application->run();
